[package]
name = "chatai"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
gpui = "0.2"
gpui-component = "0.5.0-preview2"
gpui-component-assets = "0.5.0-preview2"
rust-embed = "8.9.0"
serde = "1"
serde_json = "1.0.145"
tracing = "0.1"
